prisma-idb/idb-client-generator

packages/generator/package.json, packages/generator/src/generator.ts, packages/usage/src/lib/prisma-idb/prisma-idb-client.ts
=> Use factory pattern to initialize client

packages/generator/package.json, packages/generator/src/generator.ts, packages/usage/src/lib/prisma-idb/prisma-idb-client.ts, packages/usage/src/lib/prisma-idb/utils.ts
=> Make queries optional for some operations

packages/generator/package.json, packages/generator/src/generator.ts, packages/usage/src/lib/prisma-idb/prisma-idb-client.ts
=> Event emitters and observer pattern

packages/generator/src/Aggregate Functions/count.ts, packages/generator/src/fileBaseFunctions.ts, packages/usage/src/lib/prisma-idb/prisma-idb-client.ts, packages/usage/src/routes/+page.svelte, packages/usage/tests/test-crud.spec.ts
=> Implement count aggregate function

.github/workflows/release.yml
=> Automate Release 

packages/generator/src/Aggregate Functions/aggregate.ts, packages/generator/src/fileBaseFunctions.ts, packages/usage/src/lib/prisma-idb/prisma-idb-client.ts, packages/usage/src/prisma/schema.prisma, packages/usage/src/routes/+page.svelte
=> Implement aggregate()

.github/CODE_OF_CONDUCT.md, .github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SECURITY.md, README.md, packages/generator/src/fileCreators/prisma-idb-client/classes/PrismaIDBClient.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/routes/+page.svelte
=> Community standards

packages/generator/.release-it.json, packages/generator/package.json
=> Fix CD error due to commits during release

packages/generator/.release-it.json, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/count.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts
=> Use transactions in `count()`

.github/CONTRIBUTING.md, .github/actions/action.yml, package-lock.json, package.json, packages/usage/package.json, packages/usage/playwright.config.ts
=> Add CONTRIBUTING.md

packages/generator/src/fileCreators/idb-utils/comparator/genericComparator.ts, packages/generator/src/fileCreators/idb-utils/create.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/count.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/findMany.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_applyOrderByClause.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForFind.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_resolveOrderByKey.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_resolveSortOrder.ts, packages/usage/src/prisma/prisma-idb/idb-utils.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/tests/modelQueryOptions/orderBy.spec.ts
Implement the `orderBy()` API. Fixes #69
=> `orderBy()` API

packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/upsert.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/tests/modelQueries/upsert.spec.ts
=> `upsert()`

packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/updateMany.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/tests/modelQueries/updateMany.spec.ts
=> `updateMany()`

packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/create.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_fillDefaults.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForCreate.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_removeNestedCreateData.ts, packages/usage/playwright.config.ts, packages/usage/src/prisma/prisma-idb/idb-interface.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/prisma/schema.prisma, packages/usage/src/routes/+layout.svelte, packages/usage/src/routes/+page.svelte, packages/usage/tests/api/nestedQueries/create.spec.ts, packages/usage/tests/fixtures.ts, packages/usage/tests/queryRunnerHelper.ts
=> Explicit many to many

packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/create.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/updateMany.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/upsert.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForNestedDelete.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForUpdate.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/tests/api/nestedQueries/connectOrCreate.spec.ts, packages/usage/tests/api/nestedQueries/delete.spec.ts, packages/usage/tests/api/nestedQueries/deleteMany.spec.ts, packages/usage/tests/api/nestedQueries/disconnect.spec.ts, packages/usage/tests/api/nestedQueries/set.spec.ts, packages/usage/tests/api/nestedQueries/update.spec.ts, packages/usage/tests/api/nestedQueries/updateMany.spec.ts, packages/usage/tests/api/nestedQueries/upsert.spec.ts
Implement all the remaining nested queries. Fixes #89
=> feat: implement nested queries

package-lock.json, packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/delete.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/deleteMany.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/findUnique.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/upsert.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_fillDefaults.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForNestedDelete.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForUpdate.ts, packages/usage/package.json, packages/usage/src/lib/components/ui/button/button.svelte, packages/usage/src/lib/components/ui/input/input.svelte, packages/usage/src/lib/components/ui/select/select-content.svelte, packages/usage/src/lib/components/ui/table/table-footer.svelte, packages/usage/src/lib/components/ui/textarea/textarea.svelte, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/prisma/schema.prisma, packages/usage/tests/api/modelQueries/update.spec.ts, packages/usage/tests/api/modelQueryOptions/include.spec.ts, packages/usage/tests/api/nestedQueries/update.spec.ts, packages/usage/tests/schema/ReferentialActions/cascade.spec.ts, packages/usage/tests/schema/ReferentialActions/restrict.spec.ts, packages/usage/tests/schema/ReferentialActions/setDefault.spec.ts, packages/usage/tests/schema/ReferentialActions/setNull.spec.ts
=> 91 referential actions

packages/generator/src/fileCreators/idb-utils/comparator/genericComparator.ts, packages/usage/src/prisma/prisma-idb/idb-utils.ts
=> fix: use normal type in genericComparator to support nulls handling

packages/generator/src/fileCreators/prisma-idb-client/classes/BaseIDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/create.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/createMany.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/createManyAndReturn.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/delete.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/routes/+page.svelte, packages/usage/tests/events/create.spec.ts, packages/usage/tests/events/delete.spec.ts, packages/usage/tests/events/update.spec.ts, packages/usage/tests/queryRunnerHelper.ts
=> fix: emit events for create, update, and delete operations in IDB model classes

packages/generator/src/fileCreators/prisma-idb-client/classes/models/IDBModelClass.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/aggregate.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/tests/api/modelQueries/aggregate.spec.ts
=> feat: implement aggregate method for model class with count, sum, avg, min, and max functionalities

packages/generator/src/fileCreators/idb-utils/comparator/genericComparator.ts, packages/generator/src/fileCreators/idb-utils/create.ts, packages/generator/src/fileCreators/idb-utils/updateHandlers/BigIntHandler.ts, packages/generator/src/fileCreators/idb-utils/updateHandlers/FloatHandler.ts, packages/generator/src/fileCreators/idb-utils/updateHandlers/IntHandler.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_fillDefaults.ts, packages/usage/src/prisma/prisma-idb/idb-utils.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/prisma/schema.prisma, packages/usage/tests/api/atomicOperations.spec.ts, packages/usage/tests/api/modelQueries/create.spec.ts, packages/usage/tests/api/modelQueryOptions/select.spec.ts, packages/usage/tests/api/nestedQueries/connect.spec.ts, packages/usage/tests/queryRunnerHelper.ts, packages/usage/tests/schema/Attributes/@default.spec.ts
=> 104 atomic operators

packages/generator/src/fileCreators/idb-utils/create.ts, packages/generator/src/fileCreators/idb-utils/updateHandlers/EnumHandler.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/usage/src/prisma/prisma-idb/idb-interface.ts, packages/usage/src/prisma/prisma-idb/idb-utils.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/prisma/schema.prisma, packages/usage/tests/api/modelQueries/update.spec.ts
=> feat: add enum support with update handling and related tests

packages/generator/src/fileCreators/prisma-idb-client/classes/PrismaIDBClient.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts
Adds a feature to reset the database (clear everything)
=> feat: reset database function

packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/create.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/api/update.ts, packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_getNeededStoresForCreate.ts, packages/usage/src/prisma/prisma-idb/idb-interface.ts, packages/usage/src/prisma/prisma-idb/prisma-idb-client.ts, packages/usage/src/prisma/schema.prisma
and fix type error for deletion in optional one to one relations
=> feat: modify creation to handle models with no required fields

packages/generator/src/fileCreators/prisma-idb-client/classes/models/utils/_applyWhereClause.ts, packages/generator/src/helpers/utils.ts
Fixes: #115 
Please delete options that are not relevant.
=> fix: correct keyword ordering and field counting
